minor workflow and indent fixes

diff --git a/pwdmgr b/pwdmgr
--- a/pwdmgr
+++ b/pwdmgr
@@ -1,45 +1,48 @@
 #!/bin/bash
 
 if [ ! -e "$HOME/.pwdmgr" ]; then
-  echo "A ~/.pwdmgr file that defines GPG_PWD_FILE and TMP_PWD_FILE is missing."
-  exit 1
+    echo "A ~/.pwdmgr file that defines GPG_PWD_FILE and TMP_PWD_FILE is missing."
+    exit 1
 fi
 
 source "$HOME/.pwdmgr"
 
-if [ ! -e "$GPG_PWD_FILE" ] || [ ! -f "$GPG_PWD_FILE" ]; then
-  echo "$GPG_PWD_FILE does not exist. Create it? (y/n) "
-  read a  
-  if [ $(echo "$a" | tr '[:upper:]' '[:lower:]') = "y" ]; then
-    GPG_PWD_DIR=$(dirname "$GPG_PWD_FILE")
-    if [ ! -e "$GPG_PWD_DIR" ]; then
-      echo "$GPG_PWD_DIR does not exist. Creating it."
-      mkdir -p "$GPG_PWD_DIR"
-    fi
-    touch "$GPG_PWD_FILE"
-  else
-    echo "OK, bye."
-    exit 0
-  fi
-fi
-
 if [ -e "$TMP_PWD_FILE" ]; then
-  echo "$TMP_PWD_FILE already exists. Please, select a different file."
-  exit 1
+    echo "$TMP_PWD_FILE already exists. Please, select a different file."
+    exit 1
+else
+    TMP_PWD_DIR=$(dirname "$TMP_PWD_FILE")
+    if [ ! -e "$TMP_PWD_DIR" ]; then
+	echo "$TMP_PWD_DIR does not exist. Creating it."
+	mkdir -p "$TMP_PWD_DIR"
+    fi
 fi
 
-TMP_PWD_DIR=$(dirname "$TMP_PWD_FILE")
-
-if [ ! -e "$TMP_PWD_DIR" ]; then
-  echo "$TMP_PWD_DIR does not exist. Creating it."
-  mkdir -p "$TMP_PWD_DIR"
+if [ -d "$GPG_PWD_FILE" ]; then
+    echo "$GPG_PWD_FILE needs to be a regular file."
+    exit 1
+elif [ ! -e "$GPG_PWD_FILE" ]; then
+    echo "$GPG_PWD_FILE does not exist. Create it? (y/n) "
+    read a  
+    if [ $(echo "$a" | tr '[:upper:]' '[:lower:]') = "y" ]; then
+	GPG_PWD_DIR=$(dirname "$GPG_PWD_FILE")
+	if [ ! -e "$GPG_PWD_DIR" ]; then
+	    echo "$GPG_PWD_DIR does not exist. Creating it."
+	    mkdir -p "$GPG_PWD_DIR"
+	fi
+	touch "$GPG_PWD_FILE"
+    else
+	echo "OK, bye."
+	exit 0
+    fi
+else
+    gpg2 --output "$TMP_PWD_FILE" --decrypt "$GPG_PWD_FILE"
 fi
 
 if [ -z "$EDITOR" ]; then
-  EDITOR="emacs -q"
+    EDITOR="emacs -q"
 fi
 
-gpg2 --output "$TMP_PWD_FILE" --decrypt "$GPG_PWD_FILE"
 $EDITOR "$TMP_PWD_FILE"
 gpg2  --cipher-algo AES256 --output "$GPG_PWD_FILE" --symmetric "$TMP_PWD_FILE"
 rm -P "$TMP_PWD_FILE"*
